### ISSUE TITLE
Get PCB and find HowTo

### ISSUE THREAD

**Issue by sky321** [nekowokaburu/GeneCBR101Automation#1]
Hi,

I try to find a way to get your PCB rev. 4 or later and a HowTo for the implementation in a Gene CBR101. The current manual seems to me a little outdated.

Cheers
Chris

**Comment by nekowokaburu** [comment]
Hi Chris,

You'll find the PCB files in the GeneRev4_PCB folder. As for the manual, if you have any specific questions just ask and I would add the answers to the document. For now I decided to keep the older doc and videos for the current mod, as the depth of a manual will always depend on your level of knowledge of the area (hardware and software in this case) and the commitment on the project. I started writing an up-to-date tutorial but this takes a lot of time I'd rather spend on the project itself. Some people were also able to complete the project so far.
So if you have any concrete questions, please let me know and we can figure it out ;)

Best,
Nico
